export type ManualSection = {
  id: string;
  title: string;
  objective?: string;
  when?: string;
  body: string[];
  steps?: string[];
  result?: string;
  example?: {
    good?: string;
    bad?: string;
  };
  notes?: string[];
  warnings?: string[];
  captures: string[];
};

export type ManualChapter = {
  id: string;
  number: number;
  title: string;
  summary: string;
  sections: ManualSection[];
};

export const manualChapters: ManualChapter[] = [
  {
    id: "introduccion",
    number: 1,
    title: "Introducción",
    summary: "Qué controla el panel y cómo revisar cambios antes de publicarlos.",
    sections: [
      {
        id: "para-que-sirve",
        title: "1.1 ¿Para qué sirve el panel?",
        objective: "Entender qué partes del sitio público se controlan desde el panel.",
        when: "Antes de capacitar a una persona nueva o cuando quieras ubicar dónde se edita cada tipo de contenido.",
        body: [
          "El panel actualiza productos, categorías, contacto, sucursales y medios de trabajos realizados.",
          "Cada cambio puede afectar lo que ve el cliente en la web pública, por eso conviene revisar mensajes, badges y estados antes de guardar.",
        ],
        result: "La persona usuaria entiende que el panel no es un catálogo aislado, sino el control del contenido público.",
        warnings: ["La sección Ajustes no se incluye porque actualmente no tiene funciones relevantes para el usuario final."],
        captures: ["Vista general del panel después de iniciar sesión, señalando el sidebar", "Header superior señalando usuario, tema y botón Salir"],
      },
      {
        id: "flujo-general",
        title: "1.2 Flujo recomendado antes de publicar cambios",
        objective: "Evitar publicar contenido incompleto.",
        when: "Cada vez que se crea o edita un producto, sucursal, contacto o archivo de trabajos.",
        body: ["La forma más segura de trabajar es capturar datos, revisar advertencias, guardar y volver a Inicio para confirmar que no aparezcan pendientes importantes."],
        steps: ["Captura o edita el contenido.", "Revisa mensajes de error, badges y checklist.", "Guarda los cambios.", "Vuelve a Inicio.", "Corrige cualquier alerta de Atención inmediata."],
        result: "El contenido queda guardado con menos riesgo de errores visibles en la web pública.",
        captures: ["Formulario guardado con mensaje de confirmación", "Inicio después de guardar, señalando Atención inmediata"],
      },
    ],
  },
  {
    id: "inicio",
    number: 2,
    title: "Inicio / Dashboard",
    summary: "Lectura rápida del estado del catálogo, sucursales, contacto y medios.",
    sections: [
      {
        id: "metricas",
        title: "2.1 Revisar métricas principales",
        objective: "Saber en pocos segundos si el catálogo, sucursales y medios están completos.",
        when: "Al iniciar sesión, después de cargar productos o antes de revisar la web pública.",
        body: ["Las tarjetas superiores muestran productos publicables, imágenes cargadas, sucursales activas y medios activos. Cada tarjeta funciona como indicador y como acceso directo."],
        steps: ["Entra a Inicio.", "Revisa cada tarjeta superior.", "Da clic en la tarjeta que marque pendientes.", "Corrige la información en la sección destino."],
        result: "Identificas qué área necesita atención sin revisar manualmente todas las páginas.",
        captures: ["Dashboard completo señalando las cuatro tarjetas superiores", "Tarjeta Productos publicables señalando contador y enlace", "Tarjeta Imágenes de producto señalando productos sin foto", "Tarjeta Sucursales activas señalando sucursales con fachada", "Tarjeta Medios activos señalando archivos válidos"],
      },
      {
        id: "estado-catalogo",
        title: "2.2 Leer Estado del catálogo",
        objective: "Interpretar la distribución entre productos activos, ocultos y pendientes.",
        when: "Cuando quieres entender si el catálogo está listo o si requiere limpieza.",
        body: ["El bloque Estado del catálogo resume el inventario visible y pendiente. Las barras de salud indican imagen, categoría válida, sucursal disponible y productos publicables."],
        steps: ["Ubica Estado del catálogo.", "Revisa la distribución de productos.", "Lee Salud para publicación.", "Corrige los rubros que no estén completos."],
        result: "Sabes si el catálogo puede revisarse públicamente con confianza.",
        captures: ["Bloque Estado del catálogo completo", "Distribución de productos señalando Activos, Ocultos y Pendientes", "Salud para publicación señalando Con imagen y Publicables"],
      },
      {
        id: "atencion-inmediata",
        title: "2.3 Usar Atención inmediata",
        objective: "Corregir primero los problemas que bloquean o afectan la publicación.",
        when: "Cuando Inicio muestra estado Crítico o Revisar.",
        body: ["Atención inmediata lista alertas críticas o advertencias. Cada alerta lleva a la sección donde puede corregirse el problema."],
        steps: ["Lee la alerta.", "Da clic en la tarjeta de alerta.", "Corrige el dato pendiente.", "Guarda y vuelve a Inicio."],
        result: "Las alertas se reducen después de guardar correcciones.",
        captures: ["Bloque Atención inmediata con alerta de producto sin foto", "Pantalla destino después de dar clic en una alerta", "Estado sin bloqueos de contenido"],
      },
      {
        id: "accesos-rapidos",
        title: "2.4 Usar accesos rápidos",
        objective: "Entrar a las tareas más frecuentes sin buscar en el menú.",
        when: "Cuando necesitas gestionar productos, sucursales o trabajos desde Inicio.",
        body: ["Los accesos rápidos no guardan ni modifican información; solo te llevan a la pantalla correspondiente."],
        steps: ["Ubica Accesos rápidos.", "Presiona Gestionar productos, Editar sucursales o Actualizar trabajos.", "Realiza el cambio en la pantalla destino."],
        captures: ["Bloque Accesos rápidos señalando sus tres enlaces"],
      },
    ],
  },
  {
    id: "productos",
    number: 3,
    title: "Productos",
    summary: "Crear, editar, filtrar, activar, ocultar y eliminar fichas del catálogo.",
    sections: [
      {
        id: "lista-productos",
        title: "3.1 Ver la lista de productos",
        objective: "Revisar el estado de todas las fichas del catálogo.",
        when: "Cuando quieres auditar productos visibles, ocultos o pendientes.",
        body: ["La tabla muestra foto, producto, categoría, precio, estado, fotos, sucursales, revisión y acciones. Es la pantalla principal para detectar fichas incompletas."],
        steps: ["Entra a Productos.", "Lee las tarjetas superiores.", "Revisa la columna Revisión.", "Usa Acción para editar, activar, ocultar o eliminar."],
        result: "Sabes qué productos están listos y cuáles requieren corrección.",
        captures: ["Tabla de productos completa señalando Foto, Producto, Estado, Revisión y Acción", "Tarjetas superiores señalando Visibles en web, Borradores u ocultos y Necesitan revisión"],
      },
      {
        id: "filtrar-productos",
        title: "3.2 Filtrar productos",
        objective: "Encontrar productos por material, estado, categoría, precio, sucursal o pendientes.",
        when: "Cuando la tabla es larga o necesitas corregir un tipo específico de problema.",
        body: ["El filtro no cambia datos guardados; solo cambia lo que se muestra en pantalla. Puedes combinar varios criterios al mismo tiempo."],
        steps: ["Presiona Filtros.", "Selecciona Material, Visibilidad, Categoría, Precio, Sucursales o Solo elementos a revisión.", "Presiona Aplicar filtros.", "Presiona Limpiar para volver a la lista completa."],
        result: "La tabla queda reducida a los productos que cumplen los criterios seleccionados.",
        example: { good: "Visibilidad: No visible + Solo elementos a revisión.", bad: "Dejar filtros activos y pensar que productos desaparecieron." },
        captures: ["Botón Filtros señalado", "Panel de filtros señalando Material y Visibilidad", "Panel de filtros señalando Categoría y Precio", "Panel de filtros señalando Sucursales y Solo elementos a revisión", "Botones Aplicar filtros y Limpiar señalados"],
      },
      {
        id: "ordenar-productos",
        title: "3.3 Ordenar productos",
        objective: "Cambiar el orden de lectura de la tabla sin modificar el catálogo.",
        when: "Cuando buscas por nombre o quieres comparar precios.",
        body: ["La tabla permite ordenar por Producto y Precio. Este orden es temporal para la vista del panel."],
        steps: ["Da clic en Producto para ordenar A-Z.", "Da otro clic para invertir el orden.", "Da clic en Precio para ordenar de menor a mayor o de mayor a menor."],
        result: "La tabla se reordena, pero los productos guardados no cambian.",
        captures: ["Encabezado Producto señalando el icono de orden", "Encabezado Precio señalando el icono de orden"],
      },
      {
        id: "crear-producto",
        title: "3.4 Crear un nuevo producto",
        objective: "Registrar una ficha nueva para el catálogo.",
        when: "Cuando El Átomo Inox quiere agregar un producto que todavía no aparece en la web pública.",
        body: ["Un producto nuevo necesita nombre, código o modelo, categoría e imagen. El panel crea primero la ficha como borrador y después la publica si cumple las condiciones necesarias."],
        steps: ["Entra a Productos.", "Presiona Nuevo producto.", "Agrega la imagen principal.", "Llena nombre, código/modelo y categoría.", "Completa precio, material, medidas, descripción y observaciones si aplica.", "Revisa Visible en web.", "Presiona Crear producto."],
        result: "El panel crea el producto y te lleva a su pantalla de edición.",
        warnings: ["No se puede crear un producto sin imagen.", "El precio solo acepta dígitos, sin comas, espacios ni signos."],
        captures: ["Botón Nuevo producto señalado", "Formulario de nuevo producto completo", "Botón Crear producto señalado"],
      },
      {
        id: "campo-imagen-producto",
        title: "3.5 Campo: Imagen del producto",
        objective: "Cargar la foto principal que identifica el producto.",
        when: "Siempre que creas un producto nuevo o cuando la foto actual no representa bien el producto.",
        body: ["La imagen es obligatoria al crear. Debe mostrar el producto completo, con buena luz y sin confundirlo con otros productos."],
        steps: ["Presiona Añadir imagen o Editar imagen.", "Selecciona una imagen desde tu equipo.", "Revisa la vista previa.", "Guarda el producto."],
        result: "La imagen queda guardada como foto principal del producto.",
        example: { good: "Foto clara del carro taquero completo, sin recortes importantes.", bad: "Foto borrosa, producto cortado o imagen de otro modelo." },
        captures: ["Área Imagen del producto vacía señalando Añadir imagen", "Vista previa después de seleccionar imagen", "Mensaje de imagen obligatoria si falta al crear"],
      },
      {
        id: "campo-nombre-producto",
        title: "3.6 Campo: Nombre del producto",
        objective: "Escribir el nombre visible y entendible para el cliente.",
        when: "Al crear o corregir una ficha.",
        body: ["El nombre debe decir qué es el producto. Evita nombres internos que solo entiende el equipo."],
        steps: ["Ubica Nombre del producto.", "Escribe un nombre corto y descriptivo.", "Revisa que no repita información innecesaria del código."],
        result: "El producto se reconoce fácilmente en la tabla y en el catálogo.",
        example: { good: "Carro taquero grande en acero inoxidable", bad: "Carro 1" },
        captures: ["Campo Nombre del producto vacío con placeholder señalado", "Campo Nombre del producto lleno con ejemplo correcto"],
      },
      {
        id: "campo-codigo-producto",
        title: "3.7 Campo: Código o modelo",
        objective: "Registrar el identificador interno o modelo del producto.",
        when: "Cuando el negocio usa códigos para vender, cotizar o distinguir modelos similares.",
        body: ["Este campo es obligatorio. Ayuda al equipo a ubicar el producto correcto aunque haya nombres parecidos."],
        steps: ["Ubica Código o modelo.", "Escribe el código usado por El Átomo Inox.", "Evita textos genéricos."],
        result: "La ficha queda identificada para operación interna y revisión.",
        example: { good: "CT-120", bad: "Modelo nuevo" },
        captures: ["Campo Código o modelo señalado", "Código o modelo visible en la tabla de productos"],
      },
      {
        id: "campo-categoria-producto",
        title: "3.8 Campo: Categoría",
        objective: "Asignar el producto al grupo correcto del catálogo.",
        when: "Siempre que se crea o edita un producto.",
        body: ["La categoría agrupa el producto en la web pública."],
        steps: ["Abre el selector Categoría.", "Elige la categoría que corresponda al producto."],
        result: "El producto queda agrupado correctamente.",
        example: { good: "Carros para un carro taquero.", bad: "Una categoría que no corresponde al producto." },
        captures: ["Selector Categoría abierto"],
      },
      {
        id: "campo-precio-producto",
        title: "3.9 Campo: Precio",
        objective: "Capturar un precio numérico o dejarlo como precio a consultar.",
        when: "Cuando el producto tiene precio definido para mostrar o usar como referencia.",
        body: ["El precio es opcional. Si queda vacío, la web mostrará precio a consultar. Si se llena, solo acepta dígitos."],
        steps: ["Ubica Precio.", "Escribe solo números.", "No agregues signo de pesos, comas, espacios ni letras."],
        result: "El precio se guarda correctamente o queda como consulta si está vacío.",
        example: { good: "12500", bad: "$12,500 MXN" },
        warnings: ["Si escribes caracteres no permitidos, el formulario enfoca el campo y muestra error."],
        captures: ["Campo Precio vacío con texto de ayuda", "Campo Precio con ejemplo correcto", "Campo Precio mostrando error por caracteres inválidos"],
      },
      {
        id: "campo-material-producto",
        title: "3.10 Campo: Material",
        objective: "Indicar el material principal del producto.",
        when: "Cuando el producto es de acero inoxidable o requiere aclarar otro material.",
        body: ["Por defecto se usa Acero inoxidable. Si eliges Material distinto, aparece un campo adicional obligatorio para escribirlo."],
        steps: ["Abre Material.", "Deja Acero inoxidable si aplica.", "Elige Material distinto si corresponde.", "Escribe el material exacto en el campo adicional."],
        result: "La ficha comunica el material correcto.",
        example: { good: "Acero inoxidable", bad: "Metal bueno" },
        captures: ["Selector Material con Acero inoxidable seleccionado", "Selector Material distinto y campo adicional señalado"],
      },
      {
        id: "campo-medidas-producto",
        title: "3.11 Campo: Medidas",
        objective: "Registrar dimensiones útiles para venta o cotización.",
        when: "Cuando el tamaño ayuda al cliente a decidir o cotizar.",
        body: ["Las medidas son opcionales, pero conviene llenarlas cuando el producto tiene dimensiones estándar."],
        steps: ["Ubica Medidas.", "Escribe alto, ancho, fondo o el formato que use el negocio.", "Incluye unidades."],
        result: "El cliente y el equipo comercial entienden el tamaño del producto.",
        example: { good: "120 x 60 x 90 cm", bad: "120x60" },
        captures: ["Campo Medidas vacío", "Campo Medidas lleno con ejemplo correcto"],
      },
      {
        id: "campo-descripcion-producto",
        title: "3.12 Campo: Descripción",
        objective: "Explicar qué es el producto y para qué sirve.",
        when: "Cuando el nombre y la foto no bastan para vender o entender el producto.",
        body: ["La descripción debe ser breve, clara y útil. No necesita ser texto publicitario largo."],
        steps: ["Ubica Descripción.", "Escribe características principales.", "Menciona uso o beneficio si aplica.", "Evita párrafos demasiado largos."],
        result: "La ficha tiene contexto suficiente para clientes y vendedores.",
        example: { good: "Equipo fabricado en acero inoxidable para uso comercial intensivo.", bad: "Excelente producto de gran calidad para todo tipo de cosas." },
        captures: ["Campo Descripción señalado", "Campo Descripción lleno con ejemplo breve"],
      },
      {
        id: "campo-observaciones-producto",
        title: "3.13 Campo: Observaciones para cotización",
        objective: "Agregar aclaraciones comerciales que ayudan a cotizar.",
        when: "Cuando el producto tiene variantes, extras o condiciones que el vendedor debe considerar.",
        body: ["Este campo no reemplaza la descripción. Úsalo para detalles de cotización o notas comerciales."],
        steps: ["Ubica Observaciones para cotización.", "Escribe variantes, extras o aclaraciones.", "Revisa que no contradiga la descripción."],
        result: "El equipo tiene más contexto al atender una solicitud.",
        example: { good: "Disponible con ruedas, puertas o medidas especiales.", bad: "Bonito y barato." },
        captures: ["Campo Observaciones para cotización señalado", "Ejemplo de observación útil dentro del campo"],
      },
      {
        id: "campo-visible-producto",
        title: "3.14 Campo: Visible en web",
        objective: "Controlar si el producto puede mostrarse públicamente.",
        when: "Cuando el producto ya está listo o debe quedar oculto mientras se completa.",
        body: ["La casilla visible no reemplaza el checklist. Aunque esté marcada, el panel protege la publicación si faltan datos importantes."],
        steps: ["Marca Visible en web solo si la ficha está completa.", "Desmárcalo si el producto debe permanecer oculto.", "Guarda cambios."],
        result: "El producto queda visible u oculto según corresponda.",
        warnings: ["Si faltan datos de publicación, el panel puede impedir activarlo desde la tabla."],
        captures: ["Casilla Visible en web señalada", "Estado Visible/Oculto en la tabla de productos"],
      },
      {
        id: "editar-publicar-eliminar",
        title: "3.15 Editar, activar, ocultar o eliminar",
        objective: "Mantener actualizado el catálogo sin crear duplicados.",
        when: "Cuando una ficha ya existe y solo necesita corrección, publicación, pausa o eliminación.",
        body: ["Editar permite corregir la ficha y revisar el checklist de publicación. Activar u ocultar controla la visibilidad. Eliminar borra el producto junto con fotos, usos recomendados y relaciones con sucursales."],
        steps: ["Presiona Editar para abrir la ficha.", "Corrige datos y guarda cambios.", "Usa Activar u Ocultar desde la tabla.", "Usa Eliminar solo cuando no quieras conservar la ficha."],
        result: "La ficha queda actualizada, publicada, oculta o eliminada según la acción.",
        warnings: ["El panel no activa productos no publicables.", "Eliminar no se puede deshacer desde el panel."],
        captures: ["Botón Editar señalado en la tabla", "Checklist de publicación señalado", "Botón Activar señalado", "Botón Ocultar señalado", "Modal Eliminar producto señalado"],
      },
      {
        id: "usos-sucursales",
        title: "3.16 Usos recomendados y sucursales",
        objective: "Enriquecer la ficha con usos y disponibilidad.",
        when: "Cuando un producto aplica para giros específicos o solo está disponible en algunas sucursales.",
        body: ["Dentro de la edición de producto puedes agregar usos recomendados y relacionar sucursales. Las sucursales indican disponibilidad específica para ese producto."],
        steps: ["Abre Usos recomendados para escribir un uso.", "Presiona Agregar uso.", "Abre Sucursales.", "Presiona una sucursal para agregarla o quitarla."],
        result: "La ficha queda más útil para búsqueda, atención y disponibilidad.",
        example: { good: "Uso recomendado: Taquerías, eventos, cocina industrial.", bad: "Uso recomendado: Varios." },
        captures: ["Panel Usos recomendados cerrado", "Campo Uso recomendado lleno con ejemplo", "Panel Sucursales señalando una sucursal en estado Agregar", "Panel Sucursales señalando una sucursal Disponible"],
      },
    ],
  },
  {
    id: "categorias",
    number: 4,
    title: "Categorías",
    summary: "Consulta de categorías disponibles y productos relacionados.",
    sections: [
      {
        id: "revision-categorias",
        title: "4.1 Consultar categorías",
        objective: "Ver los grupos disponibles para clasificar productos.",
        when: "Cuando quieres revisar las categorías registradas o sus productos relacionados.",
        body: ["Categorías muestra su estado y la cantidad de productos asociados a cada una."],
        steps: ["Entra a Categorías.", "Revisa el estado y el conteo de productos de cada categoría."],
        result: "Puedes identificar las categorías disponibles para organizar productos.",
        captures: ["Tabla de categorías completa", "Columna Estado señalando Activa/Oculta", "Columna Productos señalando conteo"],
      },
    ],
  },
  {
    id: "contacto",
    number: 5,
    title: "Contacto global",
    summary: "Teléfono, WhatsApp, correo y redes sociales del sitio público.",
    sections: [
      {
        id: "guardar-contacto",
        title: "5.1 Guardar contacto principal",
        objective: "Actualizar los canales de contacto globales del sitio público.",
        when: "Cuando cambia teléfono, WhatsApp, correo o redes sociales.",
        body: ["Esta pantalla actualiza los botones de llamada, WhatsApp, correo, Instagram, Facebook y YouTube. Al guardar, el panel desactiva otros contactos principales para dejar uno solo."],
        steps: ["Actualiza los campos necesarios.", "Revisa la vista previa Así saldrá en botones.", "Presiona Guardar contacto."],
        result: "Queda un solo contacto principal activo y los botones del sitio usan esos datos.",
        warnings: ["Teléfono y WhatsApp usan 10 dígitos de México o prefijo 52.", "Instagram, Facebook y YouTube deben escribirse como URL completa."],
        captures: ["Página Contacto global completa", "Formulario de contacto señalando campos obligatorios", "Vista previa Así saldrá en botones señalada", "Mensaje de contacto guardado señalado"],
      },
      {
        id: "campo-telefono-contacto",
        title: "5.2 Campo: Teléfono de llamada",
        objective: "Definir el número que abre llamadas desde la web.",
        when: "Cuando cambia el número de atención telefónica.",
        body: ["Debe ser un número válido de México. El panel acepta 10 dígitos o prefijo 52."],
        example: { good: "5555555555", bad: "55 55 teléfono" },
        captures: ["Campo Teléfono de llamada señalado", "Ayuda de formato de teléfono abierta"],
      },
      {
        id: "campo-whatsapp-contacto",
        title: "5.3 Campo: WhatsApp",
        objective: "Definir el número que abre conversación de WhatsApp.",
        when: "Cuando cambia el número de ventas o atención por WhatsApp.",
        body: ["Debe escribirse como número válido. La vista previa muestra cómo quedará el botón."],
        example: { good: "525555555555", bad: "wa.me/mi-numero" },
        captures: ["Campo WhatsApp señalado", "Botón WhatsApp en vista previa señalado"],
      },
      {
        id: "campo-correo-contacto",
        title: "5.4 Campo: Correo",
        objective: "Definir el correo principal de contacto.",
        when: "Cuando cambia el buzón de atención.",
        body: ["Debe ser una dirección de correo completa y válida."],
        example: { good: "ventas@elatomoinox.com", bad: "ventas el atomo" },
        captures: ["Campo Correo señalado", "Botón Correo en vista previa señalado"],
      },
      {
        id: "campos-redes-contacto",
        title: "5.5 Campos: Instagram, Facebook y YouTube",
        objective: "Mantener actualizados los enlaces sociales.",
        when: "Cuando cambia un perfil, página o canal.",
        body: ["Instagram y Facebook son obligatorios. YouTube es opcional; si queda vacío, la vista previa lo muestra como sin enlace configurado."],
        example: { good: "https://instagram.com/elatomoinox", bad: "@elatomoinox" },
        captures: ["Campo Instagram señalado", "Campo Facebook señalado", "Campo YouTube señalado", "Vista previa de redes sociales señalada"],
      },
    ],
  },
  {
    id: "sucursales",
    number: 6,
    title: "Sucursales",
    summary: "Direcciones, fachada, teléfono, mapa, orden y visibilidad.",
    sections: [
      {
        id: "crear-editar-sucursal",
        title: "6.1 Crear o editar sucursal",
        objective: "Mantener actualizada la información de cada punto de venta.",
        when: "Cuando se abre una nueva sucursal o cambian dirección, teléfono, mapa, fachada u orden.",
        body: ["Cada sucursal necesita foto de fachada al crear, nombre, dirección, teléfono fijo, enlace de Google Maps, orden y estado visible en web."],
        steps: ["Presiona Nueva sucursal o Editar.", "Carga o reemplaza la fachada.", "Completa dirección, teléfono y mapa.", "Guarda los cambios."],
        result: "La sucursal queda guardada y puede aparecer en el sitio público si está visible.",
        warnings: ["La imagen de fachada se convierte a WebP.", "Si eliminas una sucursal también se borran sus relaciones con productos."],
        captures: ["Botón Nueva sucursal señalado", "Modal Nueva sucursal completo", "Botón Editar de una sucursal señalado", "Mensaje Sucursal guardada señalado"],
      },
      {
        id: "campo-fachada-sucursal",
        title: "6.2 Campo: Foto de fachada",
        objective: "Mostrar visualmente cuál es la sucursal.",
        when: "Al crear sucursal o cuando la foto ya no representa bien el lugar.",
        body: ["La fachada es obligatoria al crear. Debe verse clara y corresponder al punto de venta correcto."],
        example: { good: "Foto frontal de la sucursal con entrada visible.", bad: "Foto interior sin identificar la sucursal." },
        captures: ["Campo Foto de fachada vacío", "Vista previa de fachada cargada"],
      },
      {
        id: "campos-direccion-sucursal",
        title: "6.3 Campos: Nombre y dirección",
        objective: "Dar al cliente una ubicación clara.",
        when: "Siempre que se cree o corrija una sucursal.",
        body: ["Incluye nombre, calle y número, colonia, ciudad, estado y código postal. Todos son obligatorios."],
        example: { good: "Sucursal Centro, Av. Principal 123, Col. Centro, Guadalajara, Jalisco, 44100", bad: "Centro, por la avenida" },
        captures: ["Campo Nombre de sucursal señalado", "Campos Calle y número y Colonia señalados", "Campos Ciudad, Estado y Código postal señalados"],
      },
      {
        id: "campos-telefono-mapa-sucursal",
        title: "6.4 Campos: Teléfono fijo y Google Maps",
        objective: "Permitir que el cliente llame o abra la ubicación.",
        when: "Cuando cambia el número o se actualiza la liga de ubicación.",
        body: ["El enlace de Google Maps debe ser una URL completa. El teléfono fijo debe ser el número público de la sucursal."],
        example: { good: "https://maps.google.com/...", bad: "Buscar en Google como El Átomo" },
        captures: ["Campo Teléfono fijo señalado", "Campo Enlace de Google Maps señalado"],
      },
      {
        id: "campo-orden-visible-sucursal",
        title: "6.5 Campos: Orden y Visible en web",
        objective: "Controlar aparición y visibilidad de la sucursal.",
        when: "Cuando quieres ordenar las sucursales o esconder una temporalmente.",
        body: ["Orden usa números: los más bajos aparecen primero. Visible en web controla si la sucursal aparece públicamente."],
        example: { good: "Orden 0 para la sucursal principal.", bad: "Orden vacío en todas si se necesita priorizar una." },
        captures: ["Campo Orden de sucursal señalado", "Casilla Visible en web de sucursal señalada"],
      },
      {
        id: "visibilidad-sucursal",
        title: "6.6 Activar, ocultar o eliminar",
        objective: "Controlar si una sucursal se muestra o se borra del panel.",
        when: "Cuando una sucursal cierra temporalmente, vuelve a operar o ya no debe conservarse.",
        body: ["Activar u ocultar cambia si una sucursal aparece públicamente. Eliminar borra la sucursal, su fachada y sus relaciones con productos."],
        steps: ["Usa Activar u Ocultar desde la tabla.", "Usa Eliminar solo si no necesitas conservar la sucursal.", "Confirma la eliminación en el modal."],
        result: "La sucursal queda visible, oculta o eliminada.",
        warnings: ["Eliminar sucursal también elimina su relación con productos."],
        captures: ["Botón Activar u Ocultar de sucursal señalado", "Botón Eliminar sucursal señalado", "Modal Eliminar sucursal señalado"],
      },
    ],
  },
  {
    id: "trabajos",
    number: 7,
    title: "Trabajos",
    summary: "Videos de proceso, videos de resultados e imágenes de resultados.",
    sections: [
      {
        id: "videos-proceso",
        title: "7.1 Editar videos de proceso",
        objective: "Mantener los dos videos principales del proceso de trabajo.",
        when: "Cuando necesitas reemplazar un video de proceso.",
        body: ["Los videos de proceso están limitados a dos elementos activos. Se editan desde sus tarjetas y se mantienen activos automáticamente."],
        steps: ["Abre una tarjeta de Videos de proceso.", "Selecciona el video.", "Agrega título, alt text y orden si aplica.", "Presiona Guardar."],
        result: "El video se reemplaza y queda activo.",
        warnings: ["Los videos se comprimen a WebM, máximo 10MB y 60 segundos."],
        captures: ["Carrusel Videos de proceso completo", "Tarjeta de video de proceso señalada", "Modal de edición de video de proceso", "Campo Reemplazar medio en video de proceso señalado"],
      },
      {
        id: "videos-resultados",
        title: "7.2 Agregar o editar videos de resultados",
        objective: "Mostrar trabajos terminados en formato video.",
        when: "Cuando hay un nuevo video de resultado o uno existente debe reemplazarse.",
        body: ["Los videos de resultados tienen botón Agregar, estado Activo y opción de eliminar cuando ya existe más de un elemento en el carrusel."],
        steps: ["Presiona Agregar en Videos de resultados o abre una tarjeta existente.", "Selecciona el video.", "Completa título, alt text, orden y activo.", "Presiona Guardar."],
        result: "El video queda agregado o actualizado en el carrusel.",
        warnings: ["Debe quedar al menos un elemento en el carrusel."],
        captures: ["Carrusel Videos de resultados señalando botón Agregar", "Modal de video de resultado señalando campo Activo", "Botón Eliminar de video de resultado señalado"],
      },
      {
        id: "imagenes-resultados",
        title: "7.3 Agregar o editar imágenes de resultados",
        objective: "Mostrar trabajos terminados en formato imagen.",
        when: "Cuando hay fotos nuevas de proyectos, instalaciones o productos terminados.",
        body: ["Las imágenes de resultados se guardan como WebP de máximo 1MB. Puedes agregar, editar, ordenar, activar u ocultar."],
        steps: ["Presiona Agregar en Imágenes de resultados o abre una tarjeta existente.", "Selecciona una imagen.", "Completa título, alt text, orden y activo.", "Presiona Guardar."],
        result: "La imagen queda agregada o actualizada en el carrusel.",
        warnings: ["Debe quedar al menos un elemento en el carrusel."],
        captures: ["Carrusel Imágenes de resultados señalando botón Agregar", "Modal de imagen de resultado", "Vista del campo Reemplazar medio para imagen"],
      },
      {
        id: "campos-trabajos",
        title: "7.4 Campos del modal de trabajos",
        objective: "Llenar correctamente los datos de cada imagen o video.",
        when: "Cada vez que agregas o editas un medio.",
        body: ["Reemplazar medio es obligatorio al crear y opcional al editar. Título ayuda a identificar el archivo. Alt text describe la imagen o video. Orden define posición. Activo controla visibilidad en resultados."],
        steps: ["Selecciona archivo si vas a crear o reemplazar.", "Escribe un título claro.", "Agrega alt text descriptivo.", "Define orden si quieres priorizar.", "Marca Activo si debe aparecer."],
        result: "El medio queda comprensible, ordenado y listo para mostrarse.",
        example: { good: "Alt text: Mesa de acero inoxidable instalada en cocina comercial.", bad: "Alt text: foto" },
        warnings: ["Las imágenes se guardan como WebP de máximo 1MB.", "Los videos se guardan como WebM de máximo 10MB y 60 segundos."],
        captures: ["Campo Reemplazar medio señalado", "Campo Título señalado", "Campo Alt text señalado", "Campo Orden de aparición señalado", "Casilla Activo señalada"],
      },
    ],
  },
  {
    id: "buenas-practicas",
    number: 8,
    title: "Buenas prácticas",
    summary: "Recomendaciones para mantener el catálogo claro y confiable.",
    sections: [
      {
        id: "orden-catalogo",
        title: "8.1 Mantener orden y calidad",
        objective: "Evitar que el catálogo se vuelva difícil de revisar o entender.",
        when: "Siempre, especialmente después de cargas grandes de productos.",
        body: [
          "Usa nombres claros, códigos consistentes, imágenes nítidas y categorías bien asignadas.",
          "Antes de publicar, confirma imagen, categoría, precio si aplica, descripción, visibilidad y disponibilidad por sucursal.",
        ],
        result: "El catálogo se mantiene fácil de navegar para clientes y fácil de administrar para el equipo.",
        captures: ["Dashboard estable sin alertas críticas", "Producto completo con checklist en Listo", "Tabla de productos sin advertencias en Revisión"],
      },
      {
        id: "problemas-comunes",
        title: "8.2 Problemas comunes",
        objective: "Resolver errores frecuentes sin depender de soporte técnico.",
        when: "Cuando algo no se guarda, no aparece o muestra advertencias.",
        body: ["Si un producto no se activa, revisa el checklist. Si el precio marca error, deja solo dígitos. Si no ves todos los productos, limpia filtros. Si los cambios no aparecen en la web pública, espera hasta 5 minutos."],
        steps: ["Lee el mensaje de error o advertencia.", "Corrige el campo señalado.", "Guarda de nuevo.", "Vuelve a Inicio para verificar alertas."],
        captures: ["Checklist con un pendiente señalado", "Campo Precio mostrando error", "Botón Limpiar filtros señalado", "Mensaje de confirmación después de guardar cambios"],
      },
      {
        id: "glosario",
        title: "8.3 Glosario simple",
        objective: "Aclarar palabras que pueden confundir a usuarios no técnicos.",
        body: [
          "Visible en web: elemento que puede mostrarse en el sitio público. Oculto: elemento guardado en el panel, pero no visible públicamente. Publicable: producto que cumple condiciones para mostrarse correctamente.",
          "Alt text: descripción breve de una imagen o video. Orden: número que define qué aparece primero.",
        ],
        captures: ["Ejemplo de badge Visible/Oculto", "Campo Alt text en modal de trabajos"],
      },
    ],
  },
];

export const manualChapterMap = new Map(manualChapters.map((chapter) => [chapter.id, chapter]));
